### ISSUE TITLE
Instance downloadBackup

### ISSUE THREAD

**Issue by kamzar1** [lxdware/lxd-dashboard#2]
First of all, this is by far the most comprehensive LXD Management out there! Thanks for great work!

v. 1.2.5
instances.php
      case "downloadBackup":
        mkdir('../../downloads');
Files are pulled and written to ../../downloads.
When several users containers (especially some large containers) are pulled and stacked up there, it continues growing in webserver storage space. 

Possible solutions could be:
1. Clean up ../../download/* occasionally

2. Pull the files by curl --output /tmp/".$name.".tar.gz
This way they got a chance to disappear at some time, yet it uses server RAM.
To avoid conflicts,  output name could be:  "$project.'_'.$name.'.tar.gz'
or $file=time().'.gz' and download:
header("Content-Disposition: attachment; $name";
readfile(/tmp/$file_timestamp);  

3. I tried to download directly from api response, but it failed at some point due to large file (perhaps a filesize determining have had helped!

        $url = $url . "/1.0/instances/" . $inst_name . "/backups/" . $backup_name . "/export?project=" . $project;
        $results = shell_exec("sudo curl -k -L  --cert $cert --key $key -X GET '$url'"); // no --output
header("Content-Transfer-Encoding: chunked");
header("Content-Description: File Transfer");
header("Content-Type: application/octet-stream");
header("Cache-Control: no-cache, must-revalidate");
header("Expires: 0");
header("Content-Disposition: attachment; filename=$file_name");
//header("Content-Length: $filesize");
header("Pragma: public");
   print $results;

**Comment by matthewalanpenning** [comment]
@kamzar1 Thanks! I can see how the large backup files may be a problem. I will try out a few different option (thanks for the suggestions) and see what can be done to make it better for those larger files.

**Comment by kamzar1** [comment]
Great!
BTW, would you want to implement additional backup parameters?
{
“name”: “backupName”,
“expiry”: 1m, 
“volume_only”: true, // containers having snapshots, produce a backup tarball multiple size of original instance!
"compression_algorithm": "xz" // xz,gzip,lzma,zstd,bzip2,none //though it would fail in case those compr. libraries not loaded on host! 
}
Or you rather want keep it simple and failsafe at frontend?

**Comment by matthewalanpenning** [comment]
@kamzar1 
I think i have come up with a working solution to improve backups. Here is what I think will work
1. Change the location of the backup export files to /var/lxdware/backups. This would then place the files on mounted storage rather than simply in the container.
2. Place backup files in a hierarchy structure such as /var/lxdware/backups/<host>/<project>/<instance>/ directory - this would organize backup files and prevent confusion with backups coming from instances on different hosts and in projects other than default
3. Separate the export and download functions. Rather than exporting and downloading from the browser in a single click of a link, allow the user to click a icon link to export the LXD backup to a file, then present the user with a download link for that file.
4. Display the filesize of exported files. Because exporting larger backups can take longer than the timeout period in a web browser, displaying the filesize will allow the user to know when the exported backup is completed as their is no running LXD operation during export to monitor status.
5. Delete the exported file when deleting the backup. When deleting the LXD backup from the web interface, also delete the exported backup file to cleanup space.

Let me know your thoughts. I still want to do a little more testing, but I think it is working better.

I also will be adding additional options for backup parameters such as optimized storage, instance only, etc.

**Comment by kamzar1** [comment]
1. the location doesnt really matter, as inside a container by default there is no host storage mounted (with exception of udev and tempfs), so ../../download/ or /var/lxdware/backups either way is in container storage space.  Though in latter, you need to expand the setup by: chown -R www-data:www-data /var/lxdware/data/sqlite /var/lxdware/data/backups.
2. Good idea for better overview and control. backups/$project/$instance/$backupname'.'tar.'.$compression //gzip,xz,zstd..
Alternatively can organize them without need of subfolder structure, just drop all in one folder and name them: $host-$project-$instance-$backupname.$extension where backupname could be a timestap or some random.
3. Thats the tricky part. Depending on container size and compression algorithm, it could take a while till backup ready. I used to do all-in-one step previously and failed cause the backup was only partial file.
Two timings are to be monitored:
a.lxd api backup throughs a background operation, fetch the operation uuid and wait for it GET /1.0/operations/<uuid>/wait for it endless by long-poll API or set a timeout to let it go at some point.
b. fetching that remote into your local space, can take some time as well depends on the connection of Dashboard host to remote host. 
4. and 5. Agree.
as for the options, there was a bug in expiry syntax:
[Backup expiry](https://discuss.linuxcontainers.org/t/container-backup-expiry-ignored/10323)
So, the human friendly format "expiry": 1d, 1m .. doesnt get translated, need to use the show format. I used to generate it by:
        $expiry = date("c",strtotime("+x day"));

    {
            "name": "bk1",
            "expires_at": "2021-02-23T08:52:35.357627613+01:00",
            "instance_only": true,
            "container_only": true,
            "optimized_storage": false,
            "compression_algorithm": "xz"
    }

 Though you cant choose for users to expire their backups, perhaps they can opt-in in order to free up space sometimes.
 instance only is my proffered modus, otherwise by having snapshots, the backup size grows exponentially.
 compression_algorithm xz was best in having smallest possible backup size but worst in time and cpu usage.
 zstd and gzip quite fast and small enough.
 Yet you need to mention those by default missing libs:
 apt install xz zstd

**Comment by matthewalanpenning** [comment]
v1.2.6 has the latest updates to the backup process. I did not add the expiration time of backups yet, but will test that in a future release. The docker version already creates the new /var/lxdware/backups directory, but this will need to be created manually for other installation options, and www-data given write permissions. When backups are deleted, any locally exported file for that backup will also be deleted.
