### ISSUE TITLE
Unable to add Host

### ISSUE THREAD

**Issue by r4tze** [lxdware/lxd-dashboard#36]
Hello, yesterday I installed the lxd-dashboard locally on my server. Everything went fine. Version is 3.1.0.
The lxd-dashboard and the lxd service are on the same server. After the installation I imported the key on my console and tried to add the host. I tried it with the IP and with localhost/127.0.0.1. 
After hitting "Submit", I do not get an error, but the host does not occur in the host list. Where can I troubleshoot this issue? Are there some log files I can search?

**Comment by matthewalanpenning** [comment]
In version 3.1.0 there was a bug that affected some SQLite databases. I was binding a string to the $external_port Parameter and it should’ve been an int in the lxd-dashboard/backend/config/db.php file. This has been fixed in version 3.2.0. Depending on your web server, it will most likely log it to your default web server log location.

**Comment by r4tze** [comment]
Thanks you for the reply. I will try to update tomorrow.

**Comment by r4tze** [comment]
The updates did the trick! Thank you for your help and your awesome work!
