### ISSUE TITLE
CPU usage?

### ISSUE THREAD

**Issue by StormYudi** [lxdware/lxd-dashboard#7]
Hi, I love this project, and I am wondering if we can add a CPU usage % in dashboard?

**Comment by matthewalanpenning** [comment]
That is a great suggestion. So when I orginially wrote the code for the lxd-dashboard I had that option in there. Basically I would take calculate the amount of cycles a host CPU could run within a second of time, and then take two readings on the instance's CPU usage, one second apart from each other. That's works, but then I ran into a problem where not all servers report their CPU capabilities in the LXD Rest API. I have a limited amount of server that I test the code on and two of them did not report the CPU frequency. So I scrapped that code from the project because it only assume that many more servers will have that issue to. I can certainly take a look again at adding that and then maybe indicating an unknown CPU usage for those cases.

**Comment by matthewalanpenning** [comment]
CPU usage for each container now reads from /proc/stat of each container. Thanks for the wonderful suggestion.
